services:
  db:
    image: postgres:16-alpine
    container_name: financetracker-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ./FinanceTracker.Api
      dockerfile: Dockerfile
    container_name: financetracker-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DEFAULT_CONNECTION: ${DEFAULT_CONNECTION}
      # CORS: origin of Vite-Dev-Servers
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${API_HTTP_PORT}:8080"

  web:
    image: node:20-alpine
    container_name: financetracker-web
    working_dir: /app
    command: sh -c "npm ci && npm run dev -- --host"
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      # Browser calls API using this URL (Dev)
      VITE_API_BASE_URL: ${FRONTEND_API_BASE}
    volumes:
      - ./financetracker-web:/app
    depends_on:
      - api

  pgadmin:
    image: dpage/pgadmin4
    container_name: financetracker-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db

volumes:
  pg-data: