services:
  db:
    image: postgres:16-alpine
    container_name: financetracker-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .                         # Repo root
      dockerfile: FinanceTracker.Api/Dockerfile
    container_name: financetracker-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: "Development" # Production if live
      # Program.cs -> Environment.GetEnvironmentVariable("DEFAULT_CONNECTION")
      DEFAULT_CONNECTION: ${DEFAULT_CONNECTION}
      # Optional: CORS-Origin
      # FRONTEND_ORIGIN: "http://localhost:3000"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${API_HTTP_PORT}:8080"

  pgadmin:
    image: dpage/pgadmin4
    container_name: financetracker-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  pg-data:
